services:
  next_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sborka-web-app
    environment:
      - NODE_ENV=production
      - PORT=30002
      - HOSTNAME=0.0.0.0
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL:-http://auth-service:30001}
      - AUTH_SERVICE_FALLBACK_URL=${AUTH_SERVICE_FALLBACK_URL:-http://host.docker.internal:30001}
      - TRANSCRIBER_GATEWAY_URL=${TRANSCRIBER_GATEWAY_URL:-http://auth-service:30001/api/v1/gateway/transcriber}
    ports:
      - "${NEXT_PUBLIC_PORT:-30002}:30002"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - ibahbalezin-net
    restart: unless-stopped

networks:
  ibahbalezin-net:
    external: true
    name: ibahbalezin-net
