services:
  next_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sborka-web-app
    environment:
      - NODE_ENV=production
      - PORT=3050
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL:-http://auth-service:3001}
    ports:
      - "${NEXT_PUBLIC_PORT:-3050}:3050"
    networks:
      - ibahbalezin-net
    restart: unless-stopped

networks:
  ibahbalezin-net:
    external: true
    name: ibahbalezin-net
